"""Platform Orchestration Contracts.

Versioned schemas and adapters for cross-app Temporal workflow integration.
See ADR-036 for the full integration standard.
"""

__version__ = "0.3.0"

from .workflow_envelope import (
    WorkflowEnvelope,
    RequestedBy,
    GovernanceBlock,
    InputRef,
)
from .workflow_result import (
    WorkflowResult,
    Summary,
    ArtifactRef,
    CatalogRef,
    Warning,
    WORKFLOW_STATUS_VALUES,
)
from .workflow_ids import (
    build_workflow_id,
    build_child_workflow_id,
    parse_workflow_id,
    ParsedWorkflowId,
    VALID_DOMAINS,
)
from .artifact_manifest import (
    ArtifactManifest,
    AudioFile,
    ProvenanceBlock,
)
from .error_taxonomy import (
    WorkflowError,
    ERROR_CODES,
    validation_failed,
    resource_unavailable,
    dependency_unavailable,
    retry_exhausted,
    internal_error,
)
from .outbox import (
    WorkflowStartCommand,
    OutboxCommandStatus,
    StartResult,
    START_POLICY_TABLE,
    OUTBOX_TABLE_DDL,
    OUTBOX_STATUS_PENDING,
    OUTBOX_STATUS_DISPATCHED,
    OUTBOX_STATUS_CONFIRMED,
    OUTBOX_STATUS_FAILED,
)
from .temporal_client import (
    OrchestrationClient,
    TemporalOrchestrationClient,
    StubOrchestrationClient,
    WorkflowStatus,
    DEFAULT_NAMESPACE,
    TASK_QUEUE_CTS_WORKFLOWS,
    TASK_QUEUE_MEDIA_GPU,
    TASK_QUEUE_CASTING_WORKFLOWS,
    TASK_QUEUE_TTS_GPU,
    TASK_QUEUE_NEXUS_PUBLICATION,
    TASK_QUEUE_MEDIA_IO,
    TASK_QUEUE_SECURITY_WORKFLOWS,
    TASK_QUEUE_SECURITY_SECRET_PROVIDER,
    TASK_QUEUE_SECURITY_KUBERNETES,
    TASK_QUEUE_SECURITY_DATABASE,
    TASK_QUEUE_SECURITY_OBJECT_STORAGE,
)
from .credential_rotation import (
    SecretRef,
    ConsumerSelector,
    RotationInput,
    RotationResult,
    RotationVerification,
    RotationPolicy,
    RotationLock,
    CREDENTIAL_CLASS_POSTGRESQL_LOGIN,
    CREDENTIAL_CLASS_OBJECT_STORAGE_KEY,
    CREDENTIAL_CLASS_API_KEY,
    CREDENTIAL_CLASS_TLS_CERTIFICATE,
    CREDENTIAL_CLASS_ENCRYPTION_KEY,
    STRATEGY_DUAL_LOGIN_ROLE,
    STRATEGY_DYNAMIC_CREDENTIAL,
    STRATEGY_KEY_VERSION_ROTATION,
    STRATEGY_CERTIFICATE_RENEWAL,
    TRIGGER_SCHEDULED,
    TRIGGER_EXPOSURE,
    TRIGGER_PERSONNEL_CHANGE,
    TRIGGER_SUSPICIOUS_AUTH,
    TRIGGER_INFRASTRUCTURE_CHANGE,
    TRIGGER_MANUAL,
    ROTATION_STEPS,
    VERIFICATION_WORKLOAD_READY,
    VERIFICATION_DATABASE_CONNECTIVITY,
    VERIFICATION_READ_WRITE_PROBE,
    VERIFICATION_OBJECT_STORAGE_ACCESS,
    VERIFICATION_OLD_CREDENTIAL_REJECTED,
)

__all__ = [
    "__version__",
    # workflow_envelope
    "WorkflowEnvelope",
    "RequestedBy",
    "GovernanceBlock",
    "InputRef",
    # workflow_result
    "WorkflowResult",
    "Summary",
    "ArtifactRef",
    "CatalogRef",
    "Warning",
    "WORKFLOW_STATUS_VALUES",
    # workflow_ids
    "build_workflow_id",
    "build_child_workflow_id",
    "parse_workflow_id",
    "ParsedWorkflowId",
    "VALID_DOMAINS",
    # artifact_manifest
    "ArtifactManifest",
    "AudioFile",
    "ProvenanceBlock",
    # error_taxonomy
    "WorkflowError",
    "ERROR_CODES",
    "validation_failed",
    "resource_unavailable",
    "dependency_unavailable",
    "retry_exhausted",
    "internal_error",
    # outbox
    "WorkflowStartCommand",
    "OutboxCommandStatus",
    "StartResult",
    "START_POLICY_TABLE",
    "OUTBOX_TABLE_DDL",
    "OUTBOX_STATUS_PENDING",
    "OUTBOX_STATUS_DISPATCHED",
    "OUTBOX_STATUS_CONFIRMED",
    "OUTBOX_STATUS_FAILED",
    # temporal_client
    "OrchestrationClient",
    "TemporalOrchestrationClient",
    "StubOrchestrationClient",
    "WorkflowStatus",
    "DEFAULT_NAMESPACE",
    "TASK_QUEUE_CTS_WORKFLOWS",
    "TASK_QUEUE_MEDIA_GPU",
    "TASK_QUEUE_CASTING_WORKFLOWS",
    "TASK_QUEUE_TTS_GPU",
    "TASK_QUEUE_NEXUS_PUBLICATION",
    "TASK_QUEUE_MEDIA_IO",
    "TASK_QUEUE_SECURITY_WORKFLOWS",
    "TASK_QUEUE_SECURITY_SECRET_PROVIDER",
    "TASK_QUEUE_SECURITY_KUBERNETES",
    "TASK_QUEUE_SECURITY_DATABASE",
    "TASK_QUEUE_SECURITY_OBJECT_STORAGE",
    # credential_rotation
    "SecretRef",
    "ConsumerSelector",
    "RotationInput",
    "RotationResult",
    "RotationVerification",
    "RotationPolicy",
    "RotationLock",
    "CREDENTIAL_CLASS_POSTGRESQL_LOGIN",
    "CREDENTIAL_CLASS_OBJECT_STORAGE_KEY",
    "CREDENTIAL_CLASS_API_KEY",
    "CREDENTIAL_CLASS_TLS_CERTIFICATE",
    "CREDENTIAL_CLASS_ENCRYPTION_KEY",
    "STRATEGY_DUAL_LOGIN_ROLE",
    "STRATEGY_DYNAMIC_CREDENTIAL",
    "STRATEGY_KEY_VERSION_ROTATION",
    "STRATEGY_CERTIFICATE_RENEWAL",
    "TRIGGER_SCHEDULED",
    "TRIGGER_EXPOSURE",
    "TRIGGER_PERSONNEL_CHANGE",
    "TRIGGER_SUSPICIOUS_AUTH",
    "TRIGGER_INFRASTRUCTURE_CHANGE",
    "TRIGGER_MANUAL",
    "ROTATION_STEPS",
    "VERIFICATION_WORKLOAD_READY",
    "VERIFICATION_DATABASE_CONNECTIVITY",
    "VERIFICATION_READ_WRITE_PROBE",
    "VERIFICATION_OBJECT_STORAGE_ACCESS",
    "VERIFICATION_OLD_CREDENTIAL_REJECTED",
]
