"""Platform Orchestration Contracts.

Versioned schemas and adapters for cross-app Temporal workflow integration.
See ADR-036 for the full integration standard.
"""

__version__ = "0.4.0"

from .workflow_envelope import (
    WorkflowEnvelope,
    RequestedBy,
    GovernanceBlock,
    InputRef,
)
from .workflow_result import (
    WorkflowResult,
    Summary,
    ArtifactRef,
    CatalogRef,
    Warning,
    WORKFLOW_STATUS_VALUES,
)
from .workflow_ids import (
    build_workflow_id,
    build_child_workflow_id,
    parse_workflow_id,
    ParsedWorkflowId,
    VALID_DOMAINS,
)
from .artifact_manifest import (
    ArtifactManifest,
    AudioFile,
    ProvenanceBlock,
)
from .error_taxonomy import (
    WorkflowError,
    ERROR_CODES,
    validation_failed,
    resource_unavailable,
    dependency_unavailable,
    retry_exhausted,
    internal_error,
)
from .outbox import (
    WorkflowStartCommand,
    OutboxCommandStatus,
    StartResult,
    START_POLICY_TABLE,
    OUTBOX_TABLE_DDL,
    OUTBOX_STATUS_PENDING,
    OUTBOX_STATUS_DISPATCHED,
    OUTBOX_STATUS_CONFIRMED,
    OUTBOX_STATUS_FAILED,
)
from .temporal_client import (
    OrchestrationClient,
    TemporalOrchestrationClient,
    StubOrchestrationClient,
    WorkflowStatus,
    DEFAULT_NAMESPACE,
    TASK_QUEUE_CTS_WORKFLOWS,
    TASK_QUEUE_MEDIA_GPU,
    TASK_QUEUE_CASTING_WORKFLOWS,
    TASK_QUEUE_TTS_GPU,
    TASK_QUEUE_NEXUS_PUBLICATION,
    TASK_QUEUE_MEDIA_IO,
    TASK_QUEUE_SECURITY_WORKFLOWS,
    TASK_QUEUE_SECURITY_SECRET_PROVIDER,
    TASK_QUEUE_SECURITY_KUBERNETES,
    TASK_QUEUE_SECURITY_DATABASE,
    TASK_QUEUE_SECURITY_OBJECT_STORAGE,
)
from .credential_rotation import (
    SecretRef,
    ConsumerSelector,
    RotationInput,
    RotationResult,
    RotationVerification,
    RotationPolicy,
    RotationLock,
    AutomationTracking,
    CREDENTIAL_CLASS_POSTGRESQL_LOGIN,
    CREDENTIAL_CLASS_OBJECT_STORAGE_KEY,
    CREDENTIAL_CLASS_API_KEY,
    CREDENTIAL_CLASS_TLS_CERTIFICATE,
    CREDENTIAL_CLASS_ENCRYPTION_KEY,
    STRATEGY_DUAL_LOGIN_ROLE,
    STRATEGY_DYNAMIC_CREDENTIAL,
    STRATEGY_KEY_VERSION_ROTATION,
    STRATEGY_CERTIFICATE_RENEWAL,
    TRIGGER_SCHEDULED,
    TRIGGER_EXPOSURE,
    TRIGGER_PERSONNEL_CHANGE,
    TRIGGER_SUSPICIOUS_AUTH,
    TRIGGER_INFRASTRUCTURE_CHANGE,
    TRIGGER_MANUAL,
    ROTATION_STEPS,
    VERIFICATION_WORKLOAD_READY,
    VERIFICATION_DATABASE_CONNECTIVITY,
    VERIFICATION_READ_WRITE_PROBE,
    VERIFICATION_OBJECT_STORAGE_ACCESS,
    VERIFICATION_OLD_CREDENTIAL_REJECTED,
    # enrollment lifecycle
    LIFECYCLE_DISCOVERED,
    LIFECYCLE_BOOTSTRAP_REQUIRED,
    LIFECYCLE_ENROLLED,
    LIFECYCLE_ROTATION_READY,
    LIFECYCLE_AUTOMATICALLY_MANAGED,
    LIFECYCLE_ROTATION_DEGRADED,
    LIFECYCLE_EMERGENCY_ROTATION,
    LIFECYCLE_RETIRED,
    ALL_LIFECYCLE_STATES,
    HUMAN_ASSISTED_STATES,
    WORKFLOW_OWNED_STATES,
)
from .credential_inventory import (
    OwnerRef,
    AuthorityRef,
    ConsumerRef,
    SourceFinding,
    RiskAssessment,
    RotationCapabilities,
    CredentialSetRecord,
    DiscoveryFinding,
    EnrollmentPlan,
    EnrollmentInput,
    EnrollmentResult,
    SOURCE_KUBERNETES,
    SOURCE_GIT,
    SOURCE_RUNTIME,
    SOURCE_PROVIDER,
    SOURCE_TELEMETRY,
    SOURCE_GITLEAKS,
    ALL_DISCOVERY_SOURCES,
    EXPOSURE_UNKNOWN,
    EXPOSURE_CLEAN,
    EXPOSURE_EXPOSED_ROTATED_PENDING_ENROLLMENT,
    EXPOSURE_EXPOSED_NOT_ROTATED,
    EXPOSURE_ROTATED_ENROLLED,
    RISK_CRITICAL,
    RISK_HIGH,
    RISK_MEDIUM,
    RISK_LOW,
    ALL_RISK_TIERS,
    ENROLLMENT_MODE_OBSERVE_ONLY,
    ENROLLMENT_MODE_EXECUTE,
    ENROLLMENT_STEPS,
)

__all__ = [
    "__version__",
    # workflow_envelope
    "WorkflowEnvelope",
    "RequestedBy",
    "GovernanceBlock",
    "InputRef",
    # workflow_result
    "WorkflowResult",
    "Summary",
    "ArtifactRef",
    "CatalogRef",
    "Warning",
    "WORKFLOW_STATUS_VALUES",
    # workflow_ids
    "build_workflow_id",
    "build_child_workflow_id",
    "parse_workflow_id",
    "ParsedWorkflowId",
    "VALID_DOMAINS",
    # artifact_manifest
    "ArtifactManifest",
    "AudioFile",
    "ProvenanceBlock",
    # error_taxonomy
    "WorkflowError",
    "ERROR_CODES",
    "validation_failed",
    "resource_unavailable",
    "dependency_unavailable",
    "retry_exhausted",
    "internal_error",
    # outbox
    "WorkflowStartCommand",
    "OutboxCommandStatus",
    "StartResult",
    "START_POLICY_TABLE",
    "OUTBOX_TABLE_DDL",
    "OUTBOX_STATUS_PENDING",
    "OUTBOX_STATUS_DISPATCHED",
    "OUTBOX_STATUS_CONFIRMED",
    "OUTBOX_STATUS_FAILED",
    # temporal_client
    "OrchestrationClient",
    "TemporalOrchestrationClient",
    "StubOrchestrationClient",
    "WorkflowStatus",
    "DEFAULT_NAMESPACE",
    "TASK_QUEUE_CTS_WORKFLOWS",
    "TASK_QUEUE_MEDIA_GPU",
    "TASK_QUEUE_CASTING_WORKFLOWS",
    "TASK_QUEUE_TTS_GPU",
    "TASK_QUEUE_NEXUS_PUBLICATION",
    "TASK_QUEUE_MEDIA_IO",
    "TASK_QUEUE_SECURITY_WORKFLOWS",
    "TASK_QUEUE_SECURITY_SECRET_PROVIDER",
    "TASK_QUEUE_SECURITY_KUBERNETES",
    "TASK_QUEUE_SECURITY_DATABASE",
    "TASK_QUEUE_SECURITY_OBJECT_STORAGE",
    # credential_rotation
    "SecretRef",
    "ConsumerSelector",
    "RotationInput",
    "RotationResult",
    "RotationVerification",
    "RotationPolicy",
    "RotationLock",
    "AutomationTracking",
    "CREDENTIAL_CLASS_POSTGRESQL_LOGIN",
    "CREDENTIAL_CLASS_OBJECT_STORAGE_KEY",
    "CREDENTIAL_CLASS_API_KEY",
    "CREDENTIAL_CLASS_TLS_CERTIFICATE",
    "CREDENTIAL_CLASS_ENCRYPTION_KEY",
    "STRATEGY_DUAL_LOGIN_ROLE",
    "STRATEGY_DYNAMIC_CREDENTIAL",
    "STRATEGY_KEY_VERSION_ROTATION",
    "STRATEGY_CERTIFICATE_RENEWAL",
    "TRIGGER_SCHEDULED",
    "TRIGGER_EXPOSURE",
    "TRIGGER_PERSONNEL_CHANGE",
    "TRIGGER_SUSPICIOUS_AUTH",
    "TRIGGER_INFRASTRUCTURE_CHANGE",
    "TRIGGER_MANUAL",
    "ROTATION_STEPS",
    "VERIFICATION_WORKLOAD_READY",
    "VERIFICATION_DATABASE_CONNECTIVITY",
    "VERIFICATION_READ_WRITE_PROBE",
    "VERIFICATION_OBJECT_STORAGE_ACCESS",
    "VERIFICATION_OLD_CREDENTIAL_REJECTED",
    # enrollment lifecycle
    "LIFECYCLE_DISCOVERED",
    "LIFECYCLE_BOOTSTRAP_REQUIRED",
    "LIFECYCLE_ENROLLED",
    "LIFECYCLE_ROTATION_READY",
    "LIFECYCLE_AUTOMATICALLY_MANAGED",
    "LIFECYCLE_ROTATION_DEGRADED",
    "LIFECYCLE_EMERGENCY_ROTATION",
    "LIFECYCLE_RETIRED",
    "ALL_LIFECYCLE_STATES",
    "HUMAN_ASSISTED_STATES",
    "WORKFLOW_OWNED_STATES",
    # credential inventory (ADR-038)
    "OwnerRef",
    "AuthorityRef",
    "ConsumerRef",
    "SourceFinding",
    "RiskAssessment",
    "RotationCapabilities",
    "CredentialSetRecord",
    "DiscoveryFinding",
    "EnrollmentPlan",
    "EnrollmentInput",
    "EnrollmentResult",
    "SOURCE_KUBERNETES",
    "SOURCE_GIT",
    "SOURCE_RUNTIME",
    "SOURCE_PROVIDER",
    "SOURCE_TELEMETRY",
    "SOURCE_GITLEAKS",
    "ALL_DISCOVERY_SOURCES",
    "EXPOSURE_UNKNOWN",
    "EXPOSURE_CLEAN",
    "EXPOSURE_EXPOSED_ROTATED_PENDING_ENROLLMENT",
    "EXPOSURE_EXPOSED_NOT_ROTATED",
    "EXPOSURE_ROTATED_ENROLLED",
    "RISK_CRITICAL",
    "RISK_HIGH",
    "RISK_MEDIUM",
    "RISK_LOW",
    "ALL_RISK_TIERS",
    "ENROLLMENT_MODE_OBSERVE_ONLY",
    "ENROLLMENT_MODE_EXECUTE",
    "ENROLLMENT_STEPS",
]
